### ISSUE TITLE
TBA times causing schedulemaker to omit classes

### ISSUE THREAD

**Issue by ARamsey118** [ComputerScienceHouse/schedulemaker#102]
As of 10/21/15, EEEE-381 has a TBA for both a lab and lecture section time. This causes [this schedule](http://schedule.csh.rit.edu/schedule/a13d8) to be missing the lab section, and [this one](http://schedule.csh.rit.edu/schedule/a13d9) to be completely blank.

**Comment by bgrawi** [comment]
Thanks for pointing that out, yeah that's definitely a bug.

**Comment by jabbate19** [comment]
Will be addressed in rewrite. See #335 for updates. Closing to avoid duplicate issues
