### ISSUE TITLE
Login to save schedule

### ISSUE THREAD

**Issue by BenAlderfer** [ComputerScienceHouse/schedulemaker#103]
It would be nice to be able to login (make an account for now, use RIT login when they make this official) so I can easily save my schedules and access them later. There are other ways to save schedules but having them linked to an account would be easier. When this becomes official the account could also be tied to SIS and allow enrollment from this page.

**Comment by agargiulo** [comment]
What do you mean "when it becomes official"? Since when is RIT actually interested in SchedulMaker?

**Comment by BenAlderfer** [comment]
I don't know if they are interested but I assume it will eventually be adopted like Tiger Center was.

**Comment by mbillow** [comment]
TigerCenter was created by people who are paid by RIT (SITO), as a response to the complaints about SIS. 

TigerCenter is their official response, Schedule Maker will most likely always be completely separate.

**Comment by agargiulo** [comment]
:+1:

**Comment by agargiulo** [comment]
What else would an account buy you? If all you want is a good way to save the schedules, browser bookmarks are a good way to do that.

**Comment by BenAlderfer** [comment]
You could also add a social aspect to this where you make an account and add friends. Then you can see your friends' schedules and try to get in the same classes.

**Comment by sman591** [comment]
:+1: would probably be a lot of work but a killer feature if implemented correctly

**Comment by agargiulo** [comment]
Or just save links and share via Facebook/Twitter/etc? I don't see why this is a useful feature to add.

**Comment by bgrawi** [comment]
Accounts will likely never be added to the system in its current form. Please bookmark saved schedules in your browser instead.
