### ISSUE TITLE
Hide uncomplete schedules

### ISSUE THREAD

**Issue by bens545** [ComputerScienceHouse/schedulemaker#104]
It would be great if you had the option to only show the schedules that have all of your requested courses.  Some schedules are missing courses and make it look cluttered.

**Comment by bgrawi** [comment]
By default ScheduleMaker should not show you any schedules that are missing courses. There is an outstanding bug where a section of a selected class has a time that is TBA, it will still be added to the schedule but won't be drawn anywhere. Check to see if any of your class selections don't have a time associated with them and remove them from your cart to see if that fixes your issue in the interim.

**Comment by bens545** [comment]
Yep.  Some of the classes have times that are TBA.  Removing them fixed it.  Thanks!
