### ISSUE TITLE
Print View Doesn't Respect Sunday

### ISSUE THREAD

**Issue by billdybas** [ComputerScienceHouse/schedulemaker#109]
When clicking `Print` on a schedule, if Sunday is included in the date range, it will never show on the print page.

For example, let's use a schedule that includes two items, a course (SWEN-440) and a custom item that only happens on Sunday (Test).

This is a schedule that includes Sunday and Monday.

![sunday monday](https://cloud.githubusercontent.com/assets/13719429/18255113/c0723316-7373-11e6-8ef5-4f1416e7dacd.png)

After clicking `Print`, only Monday is shown.

![print - sunday monday](https://cloud.githubusercontent.com/assets/13719429/18255118/d5ddb428-7373-11e6-93f7-4a62f10e71d4.png)

This schedule only includes Sunday.

![sunday](https://cloud.githubusercontent.com/assets/13719429/18255125/ea13403e-7373-11e6-9f75-28c1b17669a5.png)

Clicking `Print` doesn't show Sunday; rather, it shows every other day in the week.

![print - sunday](https://cloud.githubusercontent.com/assets/13719429/18255127/f8630a66-7373-11e6-8028-a7c45d8129fd.png)

**Comment by bgrawi** [comment]
Thanks for the detailed report! I'm looking into a fix now.
