### ISSUE TITLE
Schedule Maker Courses doesnt match SIS

### ISSUE THREAD

**Issue by Vengicus** [ComputerScienceHouse/schedulemaker#116]
Im searching for Rock Climbing for Spring 2017, "Wint 39", and the available times for Wint 39-05 don't correspond to what is on SIS

![schedulemaker_error](https://cloud.githubusercontent.com/assets/22652149/19826241/b4be81d2-9d53-11e6-9304-39e0223fb3a6.PNG)

**Comment by bgrawi** [comment]
We were having an issue with importing updated class information that should now be fixed. Sorry about that!
