### ISSUE TITLE
Replace mysql library with mysqli library

### ISSUE THREAD

**Issue by bgrawi** [ComputerScienceHouse/schedulemaker#12]
_Issue by **[benrr101](https://github.com/benrr101)** from Saturday Jul 06, 2013 at 04:22 GMT_
_Originally opened as https://github.com/benrr101/schedulemaker/issues/116_

---

Or hell, maybe go all out and use PDO!

**Comment by devinmatte** [comment]
I believe @brandonhudson just completed this task in a recent commit. This issue can be closed.

**Comment by liam-middlebrook** [comment]
Fixed in https://github.com/ComputerScienceHouse/schedulemaker/commit/72724a4ce8e2630c21566ffd435706dc5dde2f7e and PR #120
