### ISSUE TITLE
For F2017: Snap to 5/10 minute mark instead of 30

### ISSUE THREAD

**Issue by ProgMetalMan** [ComputerScienceHouse/schedulemaker#125]
Fall 2017 is a week shorter than most semesters, so class lengths have been extended from 50/75/110/etc minutes to 55/80/120/etc minutes. This means that class times no longer align to the top of the hour, but to various multiples of 5 minutes. The schedules snap to the 30 minute divisions, which distorts the length of the class and breaks on the schedule. Can this be altered for this term?

**Comment by mbillow** [comment]
We are aware and @devinmatte is working on this. Thanks for reporting it!

**Comment by devinmatte** [comment]
Fixed in #126 #128
