### ISSUE TITLE
Prevent users from generating millions of schedules to avoid 500 errors.

### ISSUE THREAD

**Issue by elslush** [ComputerScienceHouse/schedulemaker#133]
![image](https://user-images.githubusercontent.com/26159293/30495155-d801a12a-9a18-11e7-9612-556f4bd024df.png)

Fatal Error when trying to generate matching schedules for Spring 2018 on chrome

**Comment by elslush** [comment]
Removing the wfit-37, wfit-76 solves the issue however

**Comment by mbillow** [comment]
Hey @elslush! Thanks for reporting this issue. Long story short, removing the WFIT classes brings your possible schedule set from >250,000 to 36,000. For the longer explanation, I am going to point you towards #118.

**Comment by bgrawi** [comment]
@devinmatte This is the most brought up "bug" in the system. Before sending a "generate schedule" request, simply multiply the number of course items and non-course items in the search. If it's greater than say 10,000 or so, just tell the user that there are too many schedules and that they need to prune down the options more. Also mention that adding Year One or other many hundereds of section classes can also cause this.
