### ISSUE TITLE
Class Times and Professors Incorrect For Spring '18

### ISSUE THREAD

**Issue by DavidIsraelChambers** [ComputerScienceHouse/schedulemaker#134]
Class times and professors do no line up with what is shown in tigercenter or SIS.  This makes the schedulemaker have marginal utility.  For specific issues, see CSCI-320, CSCI-251, and CSCI-261. For examples where times are correct, but professors are incorrect, see IGME-202

**Comment by bgrawi** [comment]
Our import script stopped working a month ago and we are looking in to it. Sorry for the inconvenience!

**Comment by bgrawi** [comment]
These should be fixed now, thanks to #136
