### ISSUE TITLE
Course names not accurate

### ISSUE THREAD

**Issue by amira1295** [ComputerScienceHouse/schedulemaker#135]
Some courses such as Wines of The World (HSPT) comes up with a course code FOOD for some reason. There are also courses on here that do not show up on SIS such as wilderness survival. Also, the times are not correct on here as someone else mentioned before. Any ETA on a fix?

**Comment by devinmatte** [comment]
@amira1295 Could you give an example of a course that is showing incorrect times?
As for the other issues we get our data dump from RIT every morning, and the dump failed to import recently. We're looking into a fix and hope to have it fixed soon.

**Comment by amira1295** [comment]
Attached is a picture of what SIS is showing for COMM-305-03. It does not
match what Schedule Maker is showing as the time. Another picture shows the
department names. SIS shows HSPT where Schedule Maker shows FOOD.

**Comment by devinmatte** [comment]
Hopefully found the fix for this. #136 Should deal with the majority of these issues.
Once it's merged and deployed I'll look to check back on this status

**Comment by bgrawi** [comment]
These are two separate issues it appears. The COMM class looks like it was fixed by #136.  The FOOD <=> HSPT thing seems to be because the department was changed separately from the course? We've been having this issue since the spring, and we'll take a look and use this issue to track it.

**Comment by devinmatte** [comment]
This has been fixed as of #142 

![screenshot from 2017-11-01 23-42-16](https://user-images.githubusercontent.com/9310513/32333229-b25f21ac-bfbd-11e7-9906-e3d58a29a387.png)
