### ISSUE TITLE
Pulling Classes That Do Not Exist

### ISSUE THREAD

**Issue by DataFrogman** [ComputerScienceHouse/schedulemaker#138]
When CRIM 210 (Technology In Criminal Justice) is added for the spring semester it shows two classes, CRIM210-01 and CRIM210-02.  On SIS and Tigercenter only CRIM210-02 exists.

**Comment by devinmatte** [comment]
We're aware of this. See #134 
A fix is in the works, see #136 and #137

**Comment by bgrawi** [comment]
This has been fixed.
