### ISSUE TITLE
Missing Classes

### ISSUE THREAD

**Issue by txk6335** [ComputerScienceHouse/schedulemaker#140]
I've been trying to put in one of my required courses, but it is not listed so there is no way for me to put it in. (INTP classes lower than 200)

**Comment by bgrawi** [comment]
I just tested this and it seems legit. We have the class in our dump file but for some reason it's not being imported correctly.

**Comment by devinmatte** [comment]
This should now be fixed

![intp-fixed](https://user-images.githubusercontent.com/9310513/32333194-9cc514c8-bfbd-11e7-9164-f1e69b604540.png)
