### ISSUE TITLE
Comm 305 error

### ISSUE THREAD

**Issue by amira1295** [ComputerScienceHouse/schedulemaker#148]
The times for Comm 305-02 and Comm 305-03 are wrong in schedule maker. There was supposedly a fix (#136) for it but it is still coming up incorrect.
![comm](https://user-images.githubusercontent.com/33226574/32793448-fe4510dc-c976-11e7-9615-64451a893b1c.PNG)

**Comment by devinmatte** [comment]
This looks like a case where SIS updated after we parsed the data dump for the day.

We get a data dump that we parse once a morning to update schedulemaker. Sadly we do not get live data from SIS. This seems like a case where SIS updated in the middle of the day, and we'd catch the update later in the day.

Checking now it appears to be accurate
