### ISSUE TITLE
Issue with saving as an "ical" 

### ISSUE THREAD

**Issue by samyck** [ComputerScienceHouse/schedulemaker#151]
"This site can’t be reached

The webpage at https://schedule.csh.rit.edu/schedule/abb89/ical might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE"

**Comment by BionicPi** [comment]
I have the same issue on windows. On macOS, it downloaded, but the file is unreadable (by either google or apple)
