### ISSUE TITLE
Can't Save As Images

### ISSUE THREAD

**Issue by dantayy** [ComputerScienceHouse/schedulemaker#156]
When clicking on the save dropdown that offers the schedule in question as either an image file or ical file, selecting the image file brings the user to a 404, with no image being created or saved, so it seems

**Comment by bgrawi** [comment]
Can confirm this -- it looks like it must be a htaccess routing problem as its hitting the redirect to the homepage instead of the api directly?

**Comment by devinmatte** [comment]
What's weird to me, is that this works perfectly fine in my dev instance on schedule-matted.csh.rit.edu

I'll have to poke around and see if I can track down the differences

**Comment by devinmatte** [comment]
It was just a permissions issue... :disappointed:
