### ISSUE TITLE
Default department number based on term

### ISSUE THREAD

**Issue by bgrawi** [ComputerScienceHouse/schedulemaker#16]
_Issue by **[benrr101](https://github.com/benrr101)** from Friday Sep 06, 2013 at 21:41 GMT_
_Originally opened as https://github.com/benrr101/schedulemaker/issues/129_

---

This is ridiculous. We know what term it is based on other info from the db, why do we need to duplicate the logic for determining which department code/number to display? Why not have a default in addition to the number and code?

**Comment by devinmatte** [comment]
@bgrawi Does this still apply to schedulemaker? And if so could you elaborate what you mean by this?

**Comment by bgrawi** [comment]
This was back in the day when departments like CSCI were like 4000- and Ben's rewrite was made right in the middle of this -- so I don't think it matters any more.
