### ISSUE TITLE
Course offerings in different time blocks will overlap when attempting to make a schedule

### ISSUE THREAD

**Issue by mxk5025** [ComputerScienceHouse/schedulemaker#161]
Explanation:
If I want to add a courses that has MWF or only F available with different time blocks, the schedule maker will try to fit both of these courses onto the schedule. The schedule should only put one course offering or check if that course is already on the schedule before adding.

**Comment by devinmatte** [comment]
So I'm not fully sure what you mean by this? Could you provide screenshots or example schedule links that show this issue?

**Comment by mxk5025** [comment]
Sending an email for the screenshots.

If there are multiple sections for a course with different time blocks (50
minutes versus 2 hour and 50 minutes), the schedule maker will put both
sections on.

So if I give a generic course without a specified section and make a
schedule this may happen.

Behavior shown here:

**Comment by mxk5025** [comment]
Actually the class was split with lab days. There was no problem after all I will close issue.
