### ISSUE TITLE
Export to iCal

### ISSUE THREAD

**Issue by SethGower** [ComputerScienceHouse/schedulemaker#176]
It would be nice to be able to export the calendars as `.ics`, similar to the functionality of TigerCenter. I would just use TigerCenter instead, but that doesn't include external thing such as work and TA sections, which I can add to ScheduleMaker.

**Comment by liam-middlebrook** [comment]
You should be able to do this already by clicking the drop-down "Save" and selecting "iCal".

![2018-08-26-164011_320x119_scrot](https://user-images.githubusercontent.com/3920942/44634425-bf7d4000-a94e-11e8-81b9-b3542d79add5.png)
