### ISSUE TITLE
Save as Image produces blank image

### ISSUE THREAD

**Issue by DanGiaime** [ComputerScienceHouse/schedulemaker#177]
![image](https://schedule.csh.rit.edu/img/schedules/712470.png) tried to save calendar as image, got this result.
Schedule in question for testing: https://schedule.csh.rit.edu/schedule/adf16
Image link:
https://schedule.csh.rit.edu/img/schedules/712470.png

**Comment by DanGiaime** [comment]
@devinmatte sorry, pasted the wrong image. Fixed now + hyperlink so you can see the image output yourself.

**Comment by devinmatte** [comment]
This will be closed after #170

**Comment by devinmatte** [comment]
It appears that imagemagick running in the docker container produces blank, white images. There may be some fonts and additional packages that we need to install or potentially it's an issue with selinux. More investigation is required
