### ISSUE TITLE
Removing a schedule after searching Matching Schedules doesn't work

### ISSUE THREAD

**Issue by CarloNapolitano** [ComputerScienceHouse/schedulemaker#183]
Im trying to create a bunch of variations of schedules and I am deleting the schedules that don't show the courses I'm trying to get and also time slots I'm not fond of.

<img width="677" alt="screen shot 2018-10-25 at 3 54 04 pm" src="https://user-images.githubusercontent.com/20861958/47526608-3a3eda80-d86e-11e8-8bfb-5b1465c0f5e4.png">

I see that schedule 89 does not have Linear Algebra so I click its remove button and watch what happens.

<img width="620" alt="screen shot 2018-10-25 at 3 55 31 pm" src="https://user-images.githubusercontent.com/20861958/47526697-868a1a80-d86e-11e8-9bab-32ed69820cf6.png">

The removed schedule does not get deleted and for some reason it re-adjusts the lower schedules. Watch what happens when I delete it again showing schedule 90 underneath it. 

<img width="609" alt="screen shot 2018-10-25 at 3 59 55 pm" src="https://user-images.githubusercontent.com/20861958/47526860-0a440700-d86f-11e8-9644-807af232c36c.png">

It gets shifted again. 

On the first page, removing a schedule works properly but if I were to go onto another page like page 6/7, the schedules that are deleted start to get shifted and not deleted. I think it is deleting a schedule on another page but I am not sure how.

**Comment by geoffmoss0** [comment]
To clarify the issue- every remove button past 3 functions incorrectly. It seems that every schedule's remove button will cause the schedule number % 3 in the list of schedules to be removed.
