### ISSUE TITLE
Schedule generation hangs indefinitely with adblocker

### ISSUE THREAD

**Issue by cjs5445** [ComputerScienceHouse/schedulemaker#189]
No matter the class selected, when I click Generate Schedules it never completes

**Comment by devinmatte** [comment]
@cjs5445 Things appear fine on my end, are you able to provide a screenshot of the request (Browser Developer tools, Network tab, select the `getMatchingSchedules` request) to maybe see what could be causing the issue for you?
I appears to be fine for me on 3 devices

**Comment by cjs5445** [comment]
Ah, now I feel like an idiot. I disabled my ad-blocker and it appears to work fine. Thanks for the quick reply.
