### ISSUE TITLE
INTP 310, 315, 325 

### ISSUE THREAD

**Issue by txk6335** [ComputerScienceHouse/schedulemaker#190]
There are quite a few interpreting classes missing :(

**Comment by devinmatte** [comment]
Hello @txk6335, What semester are you looking for?
I see 310, 315 and 325 listed on the site for Fall 2019, but not for Spring and Summer 2019, which they don't appear to be offered during.
Can you check that you've selected the correct semester from the dropdown in the right-hand corner?
