### ISSUE TITLE
Magic Spell Studios classes displaying location as null

### ISSUE THREAD

**Issue by JimDaGuy** [ComputerScienceHouse/schedulemaker#196]
My class located in Magic Spell Studios is displaying the location as null-2175
instead of MSS-2175
![capture](https://user-images.githubusercontent.com/22183239/55893472-4c93a300-5b86-11e9-927c-937459afc8e5.PNG)

**Comment by devinmatte** [comment]
Should b e fixed now.
It appears that building 71 used to be designated as the "Kiln and Casting Shop", and RIT just repurposed the number 🤔
