### ISSUE TITLE
Export/Link Schedule to Tiger Center

### ISSUE THREAD

**Issue by rmnill202** [ComputerScienceHouse/schedulemaker#198]
User Story 
===
As an RIT student, I would like the ability to export my schedule to **Tiger Center**, so that I can easily add those classes to my shopping cart.

Scope of Changes to Schedule Maker
===
- Link to Tiger Center, associated with each schedule
- URL construction that includes the `term` and `class IDs` in the query parameters

Notes
===
- There may be some error cases that need to be considered, such as trying to enroll in a past term. **Tiger Center** will definitely take care of these on our end, but the scope of exception handling in Schedule Maker is more flexible (if you'd like!)
- Tiger Center does have some branding guidelines, so we can easily share **colors** and any **iconography** that you'll need
- Classes can be identified most easily by providing the term and a SIS-specific course ID. If CSH does not have that course ID readily available, the second easiest option would be to rely on this format: `subject-catalog number-class section`. Examples: `SWEN-101-01`, `CSCI_141-02`

**Comment by devinmatte** [comment]
So on the formatting, assuming the endpoint we're hitting is something like `[GET] https://tigercenter.rit.edu/import` with query params in a similar form (params tbd) `[GET] https://tigercenter.rit.edu/import?class[]=SWEN-101-01&class[]=CSCI-141-02`

Once you have an endpoint and specs, please post them here so I can build something to test against

**Comment by devinmatte** [comment]
I'm trying out some basic design mockups to figure out location for this. There's a few options I've come up with, may need to play with the existing button layout some more:

### Option 1: Add to Share
<img width="432" alt="Screen Shot 2019-06-25 at 1 12 32 PM" src="https://user-images.githubusercontent.com/9310513/60119420-650a6700-974c-11e9-809b-fe5c2d292332.png">
Pros: Easy UI change, minimal change for the user
Cons: Not super obvious that the button should be there, which may lead to poor adoption

### Option 2: Change share to export
<img width="438" alt="Screen Shot 2019-06-25 at 1 12 55 PM" src="https://user-images.githubusercontent.com/9310513/60119421-650a6700-974c-11e9-97ea-16891b8ebb1e.png">
Pros: Easy UI change, minimal change for the user, export makes sense for location
Cons: All other options don't make as much sense as "Exports", also potentially poor adoption

### Option 3: Dedicated Button
<img width="960" alt="Screen Shot 2019-06-25 at 1 19 42 PM" src="https://user-images.githubusercontent.com/9310513/60119423-650a6700-974c-11e9-9856-c9d7cb881f0a.png">
Pros: High visibility, high adoption
Cons: Increases the menu bar size dramatically, will be hidden on smaller displays and mobile

I'm open to additional design ideas, this is just a first pass

**Comment by MoralCode** [comment]
I think it would make sense to have the existing "save" button dropdown act as the "export" (since it already has options for ics file export and export as image) and keep "share" for social media/ sharing actions. 

If the "open in tigercenter" button were part of that dropdown, then my quick-and-dirty resize-my-browser testing suggests the dropdown should still be accessible on mobile (not hurting adoption as badly) and still makes logical sense while still requiring roughly the same effort to implement.

**Comment by devinmatte** [comment]
@MoralCode Not a bad option, not sure why I didn't try that 👍

**Comment by devinmatte** [comment]
So when playing around more with the UI I've landed on what I think will be the style

<img width="424" alt="Screen Shot 2019-06-26 at 10 04 40 AM" src="https://user-images.githubusercontent.com/9310513/60186743-67c39580-97fa-11e9-9753-67f3875dca38.png">

The design evolved from these options
<img width="509" alt="Screen Shot 2019-06-26 at 10 03 26 AM" src="https://user-images.githubusercontent.com/9310513/60186741-672aff00-97fa-11e9-9ad6-56b66ce0ddc9.png">
<img width="485" alt="Screen Shot 2019-06-26 at 10 04 21 AM" src="https://user-images.githubusercontent.com/9310513/60186742-67c39580-97fa-11e9-81d2-29084d90e821.png">

The new design or more or less the same size as the current menu bar having minimal effect on mobile and smaller screen interaction.

The alt text will say `Enroll with Tiger Center`, and if you would like the icon to be the Tiger Center logo (iconography you said you can provide) that will work perfectly.

**Comment by devinmatte** [comment]
@rmnill202 I have written up the base code on my end and will have a draft PR up within the week.

If you could provide us with: 
- [ ] The endpoint you plan on having us hit (and the format of the query params)
- [ ] The iconography for the button

Then we will have everything ready on our end to simply hit merge when Tiger Center is ready

**Comment by rmnill202** [comment]
Looks great, really happy with the work being done here!

Endpoint Format
---
The endpoint that you would be hitting is `https://tigercenter.rit.edu/tigerCenterApp/login_shib/tc/enrollment/import`

For actually passing data to TC, we could just use some query strings in this format: `import?term=...&courses=...`
- Where *term* is a four-number long ID for each semester (2181, 2185, 2188)
- Where *courses* is just a CSV string of each course/section (SWEN-261-01,CSCI-344-01)

Iconography
---
For iconography, we're looking to have the Tiger Center logo included on the button. 
<img src="https://tigercenter.rit.edu/tigerCenterApp/assets/svgLib/TClogo.svg?sanitize=true" width="100" height="100" />

**Comment by devinmatte** [comment]
Blocked pending Tiger Center Enrollment being restored

**Comment by jabbate19** [comment]
Since TigerCenter is now no longer supported, I'm gonna close this

**Comment by MoralCode** [comment]
> Since TigerCenter is now no longer supported, I'm gonna close this

i believe it is, but its not great/its similar to how well schedulemaker is (was) currently supported for the past year or so (i.e. on life support/only being fixed for very broken stuff). source: I was able to get at least one ticket for an issue to be implemented by ITS (you can file help.rit.edu tickets to request improvements to TC), but it took like 2 months and i have another one thats been open for 3+ months so far. 

although the chances that enrollment gets restored are probably very low at this point so i guess the point i just made isnt actually that meaningful
