### ISSUE TITLE
Remove Google+ Share link

### ISSUE THREAD

**Issue by devinmatte** [ComputerScienceHouse/schedulemaker#199]
Google+ is discontinued, remove the share link for the service

**Comment by Jaswir** [comment]
Im on it

**Comment by Jaswir** [comment]
Nvm, will start with something easier...

**Comment by devinmatte** [comment]
Anyone who does want to pick it up, it's a 5 line change (I just counted)
`scheduleitem.html`
`shareServiceInfoFactory.js`
