### ISSUE TITLE
Course information mismatch

### ISSUE THREAD

**Issue by LeulBM** [ComputerScienceHouse/schedulemaker#219]
The information in Schedulemaker for the course CSEC-659-01 lists the course as meeting Tu/Th from 8 am - 9:15 am. However, in SIS the same course is listed as an online course with time/date TBD.

**SIS**
![image](https://user-images.githubusercontent.com/18249194/68629166-a602de00-0497-11ea-8ba7-b5d383a9761d.png)

**ScheduleMaker**
![image](https://user-images.githubusercontent.com/18249194/68629195-b6b35400-0497-11ea-89e9-8007df13fc64.png)

**Comment by devinmatte** [comment]
Appears that ScheduleMaker was just a day out of sync, should appear fixed now
