### ISSUE TITLE
Online Synchronous Course not showing in schedules for Fall 2020

### ISSUE THREAD

**Issue by photoadvisor** [ComputerScienceHouse/schedulemaker#231]
The online components of classes with synchronous components at specific times are not displaying in the weekly schedules.

Example - PHAR-202-01

**Comment by devinmatte** [comment]
The way RIT gives us the data doesn't account for this :(
I will reach out to see if RIT can give us any additional data, but I have a feeling getting this data will not be easy

**Comment by jabbate19** [comment]
Closing unless this becomes an issue again
