### ISSUE TITLE
Feedback on term change

### ISSUE THREAD

**Issue by rbuzzell** [ComputerScienceHouse/schedulemaker#28]
Is it possible to provide some kind of feedback when using the dropdown to change terms? Right now I'm not sure it did anything until I look to see the course listings.

**Comment by devinmatte** [comment]
So there is some basic feedback on term change currently, but I want to fix it to be a little more clean.

Currently there's a loading indication on all classes, that shows us next to the `x`. I have a PR to make soon that fixes that and makes the feedback more clean. But I'm wondering if anyone has any more ideas on how to add better feedback on term change?
