### ISSUE TITLE
Misspelled placeholder "(comma delmited)" 

### ISSUE THREAD

**Issue by MJE10** [ComputerScienceHouse/schedulemaker#293]
Under "Search Courses", the placeholder for the Keywords text input box says "(comma delmited)" when it should probably say "(comma delimited)"

**Comment by MoralCode** [comment]
![Screenshot_20230521_173246](https://github.com/ComputerScienceHouse/schedulemaker/assets/17362949/e8da4628-6cd6-45da-a954-35696f5d0c9a)

can confirm. submitted a PR to fix this typo

**Comment by jabbate19** [comment]
Closing as this has been fixed in dev. Will be pushed to main soon
