### ISSUE TITLE
Can't find two courses

### ISSUE THREAD

**Issue by Kms2823** [ComputerScienceHouse/schedulemaker#296]
Sofa 121 and Sofa 517 both are not showing up

**Comment by Mstrodl** [comment]
Sorry! Classes are currently being manually reimported right now to add VISL courses, try in an hour or so

**Comment by Kms2823** [comment]
Ok thanks!

**Comment by Mstrodl** [comment]
These classes should exist again now that the import has completed

**Comment by Mstrodl** [comment]
Oh, looks like not...

**Comment by Mstrodl** [comment]
Should be working now
