### ISSUE TITLE
iCal Export Dates placed wrong

### ISSUE THREAD

**Issue by jeffaburke** [ComputerScienceHouse/schedulemaker#310]
I tried exporting a schedule to a iCal format then putting it in my Google Calendar and all the days are off by a couple. For example my Monday classes were placed on Thursdays (Tuesdays -> Fridays, Wednesdays -> Saturdays and so on). Just wondering if this is an error on Googles side or on the schedule maker. Thanks

**Comment by jeffaburke** [comment]
This is similar to #232 but a little different and that issue has been open for two years now

**Comment by MoralCode** [comment]
i am seeing this issue too. for me it only starts showing my classes starting sept 1 (when they should start aug 22) and then it just continues the pattern of my classes from there. because Sept1 is a thursday, it places my wednesday and thursday classes on saturday and sunday.

**Comment by Jack-Papel** [comment]
I made a quick little workaround you can use, which is faster than manually moving the dates: [Schedule Fixer](https://github.com/Jack-Papel/schedule-fixer/)

**Comment by StoneMoney** [comment]
Just missed all my classes today because of this. My fault for not checking.

**Comment by MoralCode** [comment]
if anyone is looking for a way to download your current calendar somewhat easily (with the caveat that each session of each class is a separate event and not one repeating event per class like SM does), i recently posted a little [writeup on the RITLUG wiki](https://wiki.ritlug.com/fixing-tigercenter-calendar-download) for how i fixed a small error with TigerCenter's calendar download button by messing with the javascript on the page a little
