### ISSUE TITLE
image export/AWS is currently broken

### ISSUE THREAD

**Issue by MoralCode** [ComputerScienceHouse/schedulemaker#322]
When trying to generate or navigate to the image of a schedule it seems as though PHP is outputting an AWS related error that is causing the image data to be corrupted.

here is the error when trying to visit a (hopefully) existing schedule image (this is followed by what appears to be PNG binary image data):
> Error executing "CreateBucket" on "https://s3.csh.rit.edu/schedulemaker/"; AWS HTTP error: Server error: `PUT https://s3.csh.rit.edu/schedulemaker/` resulted in a `500 Internal Server Error` response: UnknownErrorschedulemakerUnknownErrorschedulemakertx0000079cb636c48ad0809-00649f6e2c-7ed2cf9a-default7ed2cf9a-default-default

When trying to create a schedule image via the "save" dropdown, this is the error:
> Error executing "CreateBucket" on "https://s3.csh.rit.edu/schedulemaker/"; AWS HTTP error: Server error: `PUT https://s3.csh.rit.edu/schedulemaker/` resulted in a `500 Internal Server Error` response: UnknownErrorschedulemakerUnknownErrorschedulemakertx0000048b5b93d82535574-00649f6e84-7ed2cf9a-default7ed2cf9a-default-default
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/api/src/S3Manager.php:41) in /var/www/html/api/img.php on line 31
> 
> Fatal error: Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "GetObject" on "https://s3.csh.rit.edu/schedulemaker/NaN.png"; AWS HTTP error: Client error: `GET https://s3.csh.rit.edu/schedulemaker/NaN.png` resulted in a `404 Not Found` response: <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><Message></Message><BucketName>schedulemaker</BucketN (truncated...) NoSuchKey (client): - <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><Message></Message><BucketName>schedulemaker</BucketName><RequestId>tx00000490e052dcab5192e-00649f6e84-7ed2cf9a-default</RequestId><HostId>7ed2cf9a-default-default</HostId></Error>' GuzzleHttp\Exception\ClientException: Client error: `GET https://s3.csh.rit.edu/schedulemaker/NaN.png` resulted in a `404 Not Found` response: <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><Message></Message><BucketName>schedulemaker</BucketN (truncated...) in /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestExcepti in /var/www/html/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 195

**Comment by Mstrodl** [comment]
Fixed, this was caused by upgrade to Ceph Pacific
