### ISSUE TITLE
Not producing individual Schedule Maker Link

### ISSUE THREAD

**Issue by KGriffith1** [ComputerScienceHouse/schedulemaker#323]
Hello,

When creating a schedule, I often use the 'share link' feature.  I noticed when a schedule is created, it is no longer producing an individual link, only listing "undecided".  Could this be reviewed?
![image](https://github.com/ComputerScienceHouse/schedulemaker/assets/138523653/56299ed1-cfad-44d6-a5c3-c136028fa8cf)
![Capture](https://github.com/ComputerScienceHouse/schedulemaker/assets/138523653/5e030731-ed36-4de7-8177-474d3a951622)

**Comment by MoralCode** [comment]
i suspect this may be related to #322 since the custom link generation process probably involves generating an image to save or otherwise accessing AWS (which i believe is used for the stated 3 month storage of these schedules)

**Comment by Mstrodl** [comment]
Fixed, this was caused by upgrade to Ceph Pacific
