### ISSUE TITLE
RateMyProfessors search link is out of date

### ISSUE THREAD

**Issue by MoralCode** [ComputerScienceHouse/schedulemaker#324]
All professors names are hyperlinked to RateMyProfessors, but it seems as though RateMyProfessors has updated things since these links were added to schedulemaker.

when i open up the course list to name of the first professor, this is the link i get: `http://www.ratemyprofessors.com/search.jsp?queryBy=teacherName&queryoption=HEADER&query=Melanie%20Martinek&facetSearch=true&schoolName=rochester+institute+of+technology`

this takes me to a page seemingly listing every professor on RMP.

![Screenshot_20230708_103451](https://github.com/ComputerScienceHouse/schedulemaker/assets/17362949/3b7375b5-8913-47fd-a129-1a2f1a3655ef)

Based on some of my work updating the [Rate My Professors Extension](https://github.com/CalvinWu4/RIT-Rate-My-Professors-Extension), i believe a better URL to use here would be either (obviously replacing the name)

`https://www.ratemyprofessors.com/search/professors?q=Ting%20Cao`

or (to explicitly limit results to RIT professors):

`https://www.ratemyprofessors.com/search/professors?q=${name}&sid=${schoolId}` (RIT's school id is `U2Nob29sLTgwNw==`)

**Comment by MoralCode** [comment]
looks like `rmp.php` isnt the right file ([source](https://github.com/ComputerScienceHouse/schedulemaker/pull/334#issuecomment-1874834542)).

looks like the only other two instances of "ratemyprofessors.com" in the code are
https://github.com/ComputerScienceHouse/schedulemaker/blob/0daa11ac0d25c67c8b1377509ba4bc784b5ce209/assets/src/modules/sm/App/providers/RMPUrlFilter.ts#L7

and https://github.com/ComputerScienceHouse/schedulemaker/blob/0daa11ac0d25c67c8b1377509ba4bc784b5ce209/assets/src/modules/sm/App/directives/professorLookupDirective.ts#L33

**Comment by Mstrodl** [comment]
This is fixed now

**Comment by MoralCode** [comment]
> This is fixed now

The two places in the code I linked still seem to be the same and I dont see any new commits to the repo. Can you elaborate a little more on how this is resolved?

**Comment by Mstrodl** [comment]
> The two places in the code I linked still seem to be the same and I dont see any new commits to the repo. Can you elaborate a little more on how this is resolved?

The URL you linked above is correct. 
![image](https://github.com/ComputerScienceHouse/schedulemaker/assets/6877780/8a2eb1a3-33d2-4d8b-b0ea-cfa746345b69)

**Comment by MoralCode** [comment]
Even if it works now, I believe that even the RateMyProfessors API considers that an old/legacy link format. The `807` in the urls i linked is referred to by RMP's own graphQL API as `legacyID`. I suspect that means that RMP wants to get rid of it eventually and that there's no guarantee that it will be kept around/continue to work forever (just like their old REST API). It seems like the new id format of `U2Nob29sLTgwNw==` (as i mentioned above) may be more future-proof.

**Comment by Mstrodl** [comment]
Considering I got that link from the rate my professors search page, I'm not worried about it right now? It doesn't really matter
