### ISSUE TITLE
AngularJS is EOL

### ISSUE THREAD

**Issue by MoralCode** [ComputerScienceHouse/schedulemaker#328]
https://blog.angular.io/discontinued-long-term-support-for-angularjs-cc066b82e65a

It appears as though this project still uses angularJS (i.e. angular version 1.X).

**Comment by devinmatte** [comment]
https://github.com/ComputerScienceHouse/schedulemaker/issues/200

Correct. The upgrade path is less than easy and would likely be better served by a full frontend rewrite. In absence of a full rewrite best we can do is slowly (and I do mean slowly) move up to modern angular

**Comment by MoralCode** [comment]
ah whoops, forgot to check for duplicates before posting.
