### ISSUE TITLE
Names with apostrophes are improperly formatted. 

### ISSUE THREAD

**Issue by AD417** [ComputerScienceHouse/schedulemaker#346]
Was generating a schedule when I noticed that Prob & Stat with "Richard O'Shaughnessy" places an errant backslash before the apostrophe. 
![image](https://github.com/ComputerScienceHouse/schedulemaker/assets/55056986/6e7e8428-a2cb-42ca-ad23-ce286f1f5b5b)
Similar issue appears on the class select/deselect menu:
![image](https://github.com/ComputerScienceHouse/schedulemaker/assets/55056986/53f37062-3c79-4167-be7a-9911b3c213d9)
Not sure if this error occurs when parsing SIS for the courses or when displaying them.

**Comment by Mstrodl** [comment]
Ugh. Guessing this is related to the encoding issues.

Looks like it happens during the parse step

**Comment by Mstrodl** [comment]
Oh this is actually an easy fix. Hopefully should be fixed by tomorrow, but I'll keep you posted.

**Comment by Mstrodl** [comment]
This should be fixed when the merge job happens tomorrow morning.
