### ISSUE TITLE
Schedulemaker receiving empty data dumps from SIS (No data for Spring 2025)

### ISSUE THREAD

**Issue by BrooklynFurze** [ComputerScienceHouse/schedulemaker#351]
Specific course: SWEN 444
Instructor: Sophia Sandhu
Error: Schedule maker says that Sandhu's section runs 11am-12:15pm, while SIS says that it runs 2-3:15pm. 
Semester: Spring 2025

Days are accurate, but time of day is not.

**Comment by Mstrodl** [comment]
I bugged them again yesterday and it seems like something on their end... We're getting the dumps but they're all empty! :(

**Comment by Mstrodl** [comment]
Good news! I talked with somebody at the Office of the Registrar and they made a change they believe should fix this issue when the schedulemaker dump process is run tonight!

**Comment by Mobmaker55** [comment]
ScheduleMaker is now receiving proper dumps, and the data all looks good on the site! Thank you so much @Mstrodl, and thank you to everyone for being so patient while waiting for us to resolve this :)
