### ISSUE TITLE
Schedule saving feature fails, potential regression

### ISSUE THREAD

**Issue by dax-dot-gay** [ComputerScienceHouse/schedulemaker#358]
Attempting to use the Save & Share/Direct Link buttons on individual calendars fails to generate a link, instead pointing the user at [https://schedulemaker.csh.rit.edu/undefined](https://schedulemaker.csh.rit.edu/undefined). This seems to be a regression based on closed issues #323 and possibly #322.

The result looks like this:
![image](https://github.com/user-attachments/assets/0ab6124b-08c3-4e18-9d13-e56a6311f078)

Not entirely sure if this is related, but the associated request (POST https://schedulemaker.csh.rit.edu/schedule/new) returns a PHP deprecation error as follows:

> Deprecated: This installation of the SDK is using PHP version 7.3.33, which will be deprecated on January 13th, 2025. Please upgrade your PHP version to a minimum of 8.1.x to continue receiving updates for the AWS SDK for PHP. To disable this warning, set suppress_php_deprecation_warning to true on the client constructor or set the environment variable AWS_SUPPRESS_PHP_DEPRECATION_WARNING to true. More information can be found at: https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-php-runtimes-8-0-x-and-below-in-the-aws-sdk-for-php/ in /var/www/html/vendor/aws/aws-sdk-php/src/ClientResolver.php on line 1456
{"url":"https:\/\/schedulemaker.csh.rit.edu\/schedule\/be8d9","id":"be8d9"}

---

My best guess at a possible cause is that the `getSavedAction()` function in https://github.com/ComputerScienceHouse/schedulemaker/blob/develop/assets/src/modules/sm/Schedule/directives/scheduleActionsDirective.ts expects a JSON response but is getting HTML due to the deprecation message.

**Comment by Mstrodl** [comment]
Well-researched. Thank you! Should be fixed now.
