### ISSUE TITLE
Exporting to Google Calendar Creates Separate Series

### ISSUE THREAD

**Issue by schuylermartin45** [ComputerScienceHouse/schedulemaker#63]
When I exported the calendar from Schedule Maker to Google Calendar (though I assume this may be true of other clients), it created a separate series for each class per each day the class is held.

For example, if I have Chemistry on MWF, and want to change an attribute to all instances of the class, I have to edit the Monday series, then the Wednesday series, and then the Friday series. Each class should be repeated for each day in one instance of that class.

**Comment by devinmatte** [comment]
Was told this is fixed. Closing

**Comment by natep-tech** [comment]
It looks like iCal supports repeating a VEVENT on certain days of the week using the `BYDAY` property [Recurrence Rule](https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html).

Here's a Mon/Wed/Fri class that ends on December 11th, 2023. `FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,WE,FR;UNTIL=20231211T000000Z`

**Comment by natep-tech** [comment]
#343 should fix this.
