### ISSUE TITLE
Deprecated mysql_* functions being used

### ISSUE THREAD

**Issue by RixhersAjazi** [ComputerScienceHouse/schedulemaker#70]
Hello, 

I'm a fellow RIT student and wouldn't mind contributing to this project to update it to PDO or mysqli_*

Are you guys accepting PR's?

**Comment by devinmatte** [comment]
This was fixed in #120 by @brandonhudson

**Comment by soduko** [comment]
Is there any downside to using PDO if the goal is to make the project more accessible?

**Comment by bgrawi** [comment]
I believe this has been fixed when we converted to PHP 7.
