### ISSUE TITLE
Class Length Schedule Format Problem

### ISSUE THREAD

**Issue by KChalker** [ComputerScienceHouse/schedulemaker#73]
When a schedule is made, the shorter classes show up in the schedule as the appropriate length, however this cuts off some of the class details that are needed. For example, my class that is 50 minutes will show me my class title and course code, but not my professor nor the class' location. I really need the locations on my schedule. 

Suggestion: Might be more efficient to make the blocks as big as they need to be to show all the class details, but then also accompany this with the real start and end time of the class in the blocks to avoid confusion. 

If unclear or confusing, don't hesitate to ask questions. 
Thank you so much! 
kmc1999@rit.edu

**Comment by bgrawi** [comment]
Hmm, I do see what you mean. I think this is a great idea! Thanks!
