### ISSUE TITLE
Displays Honors Courses as Lab

### ISSUE THREAD

**Issue by ARamsey118** [ComputerScienceHouse/schedulemaker#76]
**To reproduce:** Select Fall 2015 as the term and enter  EEEE-281 for the course. This results in either a lab or the honors section being placed in the schedule. (see attached screenshot)
**Expected outcome:** The honors section (EEEE-281-01H) is treated as a normal lecture section, not a lab. 
![circuits](https://cloud.githubusercontent.com/assets/9345032/6088641/a3499a0e-ae26-11e4-8e19-47022e4bba98.png)

**Comment by bgrawi** [comment]
Thanks, yeah this is definitely a new issue/side effect of trying to get lab/studio/etc sections that are also co-reqs matched at the same time. As terrible as it sounds, I can add an exception to the algorithm to ignore honors classes which will most likely be the easiest solution for now.
