### ISSUE TITLE
When professors are updated, schedulemaker doesnt update

### ISSUE THREAD

**Issue by hplewis** [ComputerScienceHouse/schedulemaker#83]
Once some of the math professors changed from TBA to actual names, schedulemaker wouldn't update completely. The actual schedule would update upon page refresh (normal), but the course selection part wouldn't update until the course was removed and then re-added. Page refresh didn't work for that.

**Comment by bgrawi** [comment]
Like I mentioned to you in person, this is really hard to do and is really only an edge case while they are finalizing teachers.
