### ISSUE TITLE
 The requested schedule was not found.

### ISSUE THREAD

**Issue by abrahamw88** [ComputerScienceHouse/schedulemaker#89]
Most of the time when I save a schedule to a link and open that link on another device it gives me the error " The requested schedule was not found.". But usually I can open it on the same device that I created it on. Any ideas? 
for example the link here: http://schedule.csh.rit.edu/schedule/a05a6
![image](https://cloud.githubusercontent.com/assets/4059967/7273935/5d26fce4-e8c6-11e4-8999-2a019bc0aaf2.png)

**Comment by bgrawi** [comment]
Hmm, I have noticed this problem in isolated incidents, especially if the other device is a mobile phone. I wan't able to consistently reproduce this problem, but I will definitely look into it more.

Does refreshing the page on the other device (shown in the screenshot) allow the schedule to be shown?  The problem may be related to a race condition or a caching issue and reloading the page sometimes fixes the problem for me.

**Comment by bgrawi** [comment]
I'm pretty sure this was the same issue as #94. It has been fixed in commit 99830038d2e63fd8dbf4fb4c7e082cb43154d8d9
