### ISSUE TITLE
Instructions on how to use the generate schedule

### ISSUE THREAD

**Issue by jackyliang** [ComputerScienceHouse/schedulemaker#91]
Hi there.

I would LOVE to use your generate schedule tool, as I am working on a site like this for my school as well. 

What are the data structures required to go into the generate class?

**Comment by bgrawi** [comment]
Hi! This is a common question asked here, I'll close this in favor of #56. But to specifically answer your question, our schema is outlined in [this folder] (https://github.com/ComputerScienceHouse/schedulemaker/tree/master/schema). To get the data in this format really depends on what system your college uses. RIT uses a heavily customized version of Oracle's Peoplesoft, so our [import script](https://github.com/ComputerScienceHouse/schedulemaker/blob/master/tools/processDump.php) is very tuned to that and would almost certainly not work for other colleges. Generally, you would have to write your own importer that would be able to match our schema. This will likely be very challenging and it may be more worth it to write your own system and just to use ours as a reference or starting-off point. 

This may change in the future if we decide to make ScheduleMaker itself more portable, but as of right now, there are no plans in motion. Thanks for checking us out though -- and good luck with your project!
