### ISSUE TITLE
Use of special characters in Non-Course scheduled items

### ISSUE THREAD

**Issue by sidewinder12s** [ComputerScienceHouse/schedulemaker#95]
Using an ampersand (&) in the name of a Non-Course Scheduled Item causes the displayed name in the generated schedule to use the I think HTML code for it. Also throws off the formatting relative to the rest of the generated schedule. 

Course Name: Vini & Viti

Expected name in schedule: Vini & Viti
Actual: Vini amp Viti

![screen shot 2015-08-30 at 2 35 32 pm](https://cloud.githubusercontent.com/assets/1393426/9568829/6cce5560-4f24-11e5-8701-cd0124acdd25.png)

**Comment by JoelEager** [comment]
I checked and this issue doesn't exist in the current version of schedule maker:
![image](https://cloud.githubusercontent.com/assets/14286106/10413115/b1cddb14-6f6c-11e5-8dd9-66f61bd45b9a.png)
