### ISSUE TITLE
Schedule Conflict not Detected when Lab Present

### ISSUE THREAD

**Issue by wastevensv** [ComputerScienceHouse/schedulemaker#97]
In the schedule below it states that CMPE-160-01 can't be displayed because the time/date range is too narrow when the lecture actually has a scheduling conflict with PHYS-211-04. Therefore this schedule shouldn't have been suggested in the first place. The lab for CMPE-160-01 was placed in the schedule, which leads me to believe that it is an issue with how lectures and labs are handled.
Example Schedule for Reference:
http://schedule.csh.rit.edu/schedule/a1162

**Comment by sman591** [comment]
Seems like this might actually be with how the lecture was scheduled? Zooming the schedule out to the maximum view exposes the class is scheduled at 2am... http://schedule.csh.rit.edu/schedule/a116e

**Comment by wastevensv** [comment]
That explains it. So an issue with whoever scheduled the course, not with the application. Thanks!
